<?php

class LoginController extends MainController{
    protected $module_name = 'login';
    function __construct($parameters = null){
              
        parent::__construct($parameters,$this->module_name,false);
    }

    public function index($response = null){               
        $this->title = 'Login';        
        require ABSPATH . '/views/login/login-view.php';
    }
    
    function acess(){
        try{

            if(!isset($_POST["email"]) || empty($_POST["email"])){
                $response['cod']       = 1;
                $response['input']     = $_POST;               
                $response['message'] = "inform the email";
                throw new Exception(json_encode($response),1);
            }
            
            if(!isset($_POST["password"]) || empty($_POST["password"])){
                $response['cod']     = 1;
                $response['input']   = $_POST;             
                $response['message'] = "inform the password";
                throw new Exception(json_encode($response),1);
            }else{
                $hash_post = md5($_POST['password']);
            }
                            
            $user = json_decode($this->model->getUser($_POST['email']));
            if(!isset($user) || empty($user)){
                $response['cod']     = 1;         
                $response['input']   = $_POST;      
                $response['message'] = "invalid user";
                throw new Exception(json_encode($response),1);
            }else{
                $hash_pass =$user[0]->password; 
            }
    
            if($hash_pass == $hash_post){                                          
                $this->setSession($user[0]->email);                          
            }else{
                $response['cod']     = 1; 
                $response['input']   = $_POST;             
                $response['message'] = "username or password is invalid";
                throw new Exception(json_encode($response),1);
            }

           
        }catch(Exception $e){            
           $this->index($response);  
        }        
    }

    function finish(){        
        parent::logout(true); // TODO: Change the autogenerated stub
    }
} 